# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='identifier',
            field=models.CharField(max_length=16, unique=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last timestamp'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('timestamp', 'vehicle')]),
        ),
    ]
