# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_various_fixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('id',), 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('-last_location__timestamp',), 'verbose_name': 'vehicle', 'verbose_name_plural': 'vehicles'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_timestamp',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_location_vehicle', to='vehicles.Location', verbose_name='last_location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(db_index=True, verbose_name='timestamp'),
        ),
    ]
